name: msa_app
description: Malnutrition Screening Case Study Thai Otsuka Company Application Project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  cupertino_icons: ^1.0.2
  flutter_feather_icons: ^2.0.0
  auto_size_text: ^3.0.0
  custom_radio_grouped_button: ^2.1.2+2
  printing: ^5.9.3
  syncfusion_flutter_charts: ^20.3.47
  flutter_translate: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  fonts:
    - family: Prompt
      fonts:
        - asset: assets/fonts/Prompt-Bold.ttf
        - asset: assets/fonts/Prompt-Italic.ttf
        - asset: assets/fonts/Prompt-Medium.ttf
        - asset: assets/fonts/Prompt-Regular.ttf
  assets:
    - assets/images/
    - assets/i18n/th.json
    - assets/i18n/en.json

  uses-material-design: true
